package app.domain.enums;

public enum UserRole {
    NATURAL_PERSON_CLIENT,
    COMPANY_CLIENT,
    TELLER_EMPLOYEE,
    COMMERCIAL_EMPLOYEE,
    COMPANY_OPERATIVE,
    COMPANY_SUPERVISOR,
    INTERNAL_ANALYST
}