spring.application.name=bank

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=BankDB;encrypt=true;trustServerCertificate=true;instanceName=SQLEXPRESS
spring.datasource.username=sa
spring.datasource.password=Bank123!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver